# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter
name: Run Formatter on episode transcripts

on:
  push:
    branches: [ master ]
  workflow_dispatch: # create a button to run on demand
#   pull_request:
#     branches: [ master ]
jobs:
  run-formatter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
    
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}- 
    
      - name: run npm install
        run: npm install
        
      - name: run formatter
        run: |-
          npm run format
          git status
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Apply Formatting linter to show-notes
          title: Apply Formatting linter to show-notes
          body: |-
            This pull request was automatically generated by a github action. 
            It ran `npm run format` after the last push to master, which was
            *${{ github.event.head_commit.message }}*
          branch: action-format
          delete: true
