name: Commit timestamp to repo

on:
  # push:
  workflow_dispatch: # create a button to run on demand
jobs:
  add-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Check if triggered by this action
        if: github.actor == 'simeycodes'
        run: |-
          echo "exiting to prevent infinite loop"
          echo ${{ github.actor }}
          exit 1 
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_PAT }}
        
      - name: create timestamp
        run: |-
          date >> timestamps.txt
          echo ${{ github.actor }}
      
      - name: Commit and push if it changed
        if: ${{ github.actor}} != 'simeycodes'
        run: |-
          echo ${{ github.actor }}
          git config user.name "simeycodes"
          git config user.email "92826264+simeycodes@users.noreply.github.com"
          git add -A
          git commit -m "Add timestamp"
          git push

      ## Alternative to Automatic Push. 
      ## Left here in case we ever want to go back to PR instead of push
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     commit-message: Apply standardized formatter to transcripts
      #     title: Apply standardized formatter to transcripts
      #     body: |-
      #       This pull request was automatically generated by a GitHub Action.
      #       It ran `npm run format` after the last push to master, which was
      #       *${{ github.event.head_commit.message }}*
      #     branch: action-format
      #     delete-branch: true
